/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;
import javax.swing.JInternalFrame;

/**
 *
 * @author Asus
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpsFondo = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuMantenedor = new javax.swing.JMenu();
        mnuiAgencia = new javax.swing.JMenuItem();
        mnuiGaraje = new javax.swing.JMenuItem();
        mnuiCliente = new javax.swing.JMenuItem();
        mnuiAutomovil = new javax.swing.JMenuItem();
        mnuListado = new javax.swing.JMenu();
        mnuiListarAgencias = new javax.swing.JMenuItem();
        mnuiListarGarajes = new javax.swing.JMenuItem();
        mnuiListarClientes = new javax.swing.JMenuItem();
        mnuiListarAutomovil = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dpsFondoLayout = new javax.swing.GroupLayout(dpsFondo);
        dpsFondo.setLayout(dpsFondoLayout);
        dpsFondoLayout.setHorizontalGroup(
            dpsFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 852, Short.MAX_VALUE)
        );
        dpsFondoLayout.setVerticalGroup(
            dpsFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        mnuMantenedor.setText("Mantenedores");

        mnuiAgencia.setText("Agencia");
        mnuiAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiAgenciaActionPerformed(evt);
            }
        });
        mnuMantenedor.add(mnuiAgencia);

        mnuiGaraje.setText("Garaje");
        mnuiGaraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiGarajeActionPerformed(evt);
            }
        });
        mnuMantenedor.add(mnuiGaraje);

        mnuiCliente.setText("Cliente");
        mnuiCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiClienteActionPerformed(evt);
            }
        });
        mnuMantenedor.add(mnuiCliente);

        mnuiAutomovil.setText("Automovil");
        mnuiAutomovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiAutomovilActionPerformed(evt);
            }
        });
        mnuMantenedor.add(mnuiAutomovil);

        jMenuBar1.add(mnuMantenedor);

        mnuListado.setText("Listados");

        mnuiListarAgencias.setText("Listado de Agencias");
        mnuiListarAgencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiListarAgenciasActionPerformed(evt);
            }
        });
        mnuListado.add(mnuiListarAgencias);

        mnuiListarGarajes.setText("Listado de Garajes");
        mnuiListarGarajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiListarGarajesActionPerformed(evt);
            }
        });
        mnuListado.add(mnuiListarGarajes);

        mnuiListarClientes.setText("Listado de Clientes");
        mnuiListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiListarClientesActionPerformed(evt);
            }
        });
        mnuListado.add(mnuiListarClientes);

        mnuiListarAutomovil.setText("Listado de Automoviles");
        mnuiListarAutomovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiListarAutomovilActionPerformed(evt);
            }
        });
        mnuListado.add(mnuiListarAutomovil);

        jMenuBar1.add(mnuListado);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpsFondo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dpsFondo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuiAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiAgenciaActionPerformed
        ifrmAgencia ifrAgencia = new ifrmAgencia();
        centrarInternalFrame(ifrAgencia);
    }//GEN-LAST:event_mnuiAgenciaActionPerformed

    private void mnuiListarAgenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiListarAgenciasActionPerformed
        // TODO add your handling code here:
        ifrmListadoAgencia ifrmListadoAgencia = new ifrmListadoAgencia();
        centrarInternalFrame(ifrmListadoAgencia);
    }//GEN-LAST:event_mnuiListarAgenciasActionPerformed

    private void mnuiGarajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiGarajeActionPerformed
        // TODO add your handling code here:
        ifrmGaraje ifrmGaraje = new ifrmGaraje();
        centrarInternalFrame(ifrmGaraje);
    }//GEN-LAST:event_mnuiGarajeActionPerformed

    private void mnuiListarGarajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiListarGarajesActionPerformed
        // TODO add your handling code here:
        ifrmListadoGaraje ifrmListadoGaraje1 = new ifrmListadoGaraje();
        centrarInternalFrame(ifrmListadoGaraje1);
    }//GEN-LAST:event_mnuiListarGarajesActionPerformed

    private void mnuiClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiClienteActionPerformed
        // TODO add your handling code here:
        ifrmCliente ifrmCliente1 = new ifrmCliente();
        centrarInternalFrame(ifrmCliente1);
    }//GEN-LAST:event_mnuiClienteActionPerformed

    private void mnuiListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiListarClientesActionPerformed
        // TODO add your handling code here:
        ifrmListadoCliente ifrmListadoCliente1= new ifrmListadoCliente();
        centrarInternalFrame(ifrmListadoCliente1);
    }//GEN-LAST:event_mnuiListarClientesActionPerformed

    private void mnuiAutomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiAutomovilActionPerformed
        // TODO add your handling code here:
        ifrmAutomoviles ifrmAutomoviles = new ifrmAutomoviles();
        centrarInternalFrame(ifrmAutomoviles);
    }//GEN-LAST:event_mnuiAutomovilActionPerformed

    private void mnuiListarAutomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiListarAutomovilActionPerformed
        // TODO add your handling code here:
        ifrmListadoAutomoviles ifrmListadoAutomoviles1= new ifrmListadoAutomoviles();
        centrarInternalFrame(ifrmListadoAutomoviles1);
    }//GEN-LAST:event_mnuiListarAutomovilActionPerformed
public void centrarInternalFrame(JInternalFrame interna) {
        int x, y;
        x = dpsFondo.getWidth()/2 - interna.getWidth()/2;
        y = dpsFondo.getHeight()/2 - interna.getHeight()/2;
        if(interna.isShowing())
            interna.setLocation(x, y);
        else {
            dpsFondo.add(interna);
            interna.setLocation(x, y);
            interna.show();
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    //llamar a ifrm
//    ifrmname ifrname = new Ifrmname();
//    centrarInternalFrame(ifrname);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpsFondo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuListado;
    private javax.swing.JMenu mnuMantenedor;
    private javax.swing.JMenuItem mnuiAgencia;
    private javax.swing.JMenuItem mnuiAutomovil;
    private javax.swing.JMenuItem mnuiCliente;
    private javax.swing.JMenuItem mnuiGaraje;
    private javax.swing.JMenuItem mnuiListarAgencias;
    private javax.swing.JMenuItem mnuiListarAutomovil;
    private javax.swing.JMenuItem mnuiListarClientes;
    private javax.swing.JMenuItem mnuiListarGarajes;
    // End of variables declaration//GEN-END:variables
}
