/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;
import datos.*;
import entidades.*;
import logica.*;
import com.toedter.calendar.JDateChooser;
import java.util.GregorianCalendar;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
/**
 *
 * @author Asus
 */
public class ifrmRegistrarReserva extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrmname
     */
    public ifrmRegistrarReserva() {
        initComponents();
        initComponentsCustom();
    }
    private void initComponentsCustom() {
        facade = new FacadeAlquiler();

        // Crear JDateChoosers
        dateInicio = new JDateChooser();
        dateFin = new JDateChooser();

        // Crear spinners para horas y minutos
        timeInicioHora = new JSpinner(new SpinnerNumberModel(9, 0, 23, 1)); // 9 AM por defecto
        timeInicioMinuto = new JSpinner(new SpinnerNumberModel(0, 0, 59, 1));
        timeFinHora = new JSpinner(new SpinnerNumberModel(17, 0, 23, 1)); // 5 PM por defecto
        timeFinMinuto = new JSpinner(new SpinnerNumberModel(0, 0, 59, 1));

        // Posicionar componentes (ajusta según tu layout)
        dateInicio.setBounds(183, 150, 130, 22);
        timeInicioHora.setBounds(320, 150, 50, 22);
        timeInicioMinuto.setBounds(375, 150, 50, 22);

        dateFin.setBounds(183, 180, 130, 22);
        timeFinHora.setBounds(320, 180, 50, 22);
        timeFinMinuto.setBounds(375, 180, 50, 22);

        // Añadir al contenedor
        getContentPane().add(dateInicio);
        getContentPane().add(timeInicioHora);
        getContentPane().add(timeInicioMinuto);
        getContentPane().add(dateFin);
        getContentPane().add(timeFinHora);
        getContentPane().add(timeFinMinuto);

        cargarClientes();
        cargarAgencias();
        activar(false);
    }
    private void cargarClientes() {
        try {
            ArrayList<Cliente> clientes = facade.listarClientes();
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement("Seleccione un cliente...");

            for (Cliente cliente : clientes) {
                model.addElement(cliente.getIdCliente() + " - " + cliente.getNombre());
            }
            jComboBox1.setModel(model);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error al cargar clientes: " + e.getMessage(), 
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cargarAgencias() {
        try {
            ArrayList<Agencia> agencias = facade.listarAgencias();
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement("Seleccione una agencia...");

            for (Agencia agencia : agencias) {
                model.addElement(agencia.getAgenciaId() + " - " + agencia.getNombre());
            }
            jComboBox2.setModel(model);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error al cargar agencias: " + e.getMessage(), 
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void activar(boolean estado) {
        jComboBox1.setEnabled(estado);
        jComboBox2.setEnabled(estado);
        dateInicio.setEnabled(estado);
        dateFin.setEnabled(estado);
        timeInicioHora.setEnabled(estado);
        timeInicioMinuto.setEnabled(estado);
        timeFinHora.setEnabled(estado);
        timeFinMinuto.setEnabled(estado);
        btnRegistrar.setEnabled(estado);
    }

    private void limpiar() {
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        dateInicio.setDate(null);
        dateFin.setDate(null);
        timeInicioHora.setValue(9);
        timeInicioMinuto.setValue(0);
        timeFinHora.setValue(17);
        timeFinMinuto.setValue(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    @Override
    public void dispose() {
        super.dispose(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAgencia = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblDniCliente = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setTitle("Registro de Reservas");

        lblAgencia.setText("Agencia");

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24-em-plus.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.gif"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setEnabled(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24-em-cross.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblDniCliente.setText("Cliente");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Fecha de inicio");

        jLabel2.setText("Fecha Fin");

        jLabel3.setText("Fecha");

        jLabel4.setText("Hora");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 121, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblDniCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(lblAgencia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, 192, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel4)
                        .addGap(142, 142, 142))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        activar(true);
        limpiar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
            try {
            // Obtener cliente seleccionado
            String clienteSeleccionado = (String) jComboBox1.getSelectedItem();
            if (clienteSeleccionado == null || clienteSeleccionado.equals("Seleccione un cliente...")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente");
                return;
            }
            int clienteId = Integer.parseInt(clienteSeleccionado.split(" - ")[0]);

            // Obtener agencia seleccionada
            String agenciaSeleccionada = (String) jComboBox2.getSelectedItem();
            if (agenciaSeleccionada == null || agenciaSeleccionada.equals("Seleccione una agencia...")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una agencia");
                return;
            }
            int agenciaId = Integer.parseInt(agenciaSeleccionada.split(" - ")[0]);

            // Obtener fechas
            if (dateInicio.getDate() == null || dateFin.getDate() == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar las fechas de inicio y fin");
                return;
            }

            GregorianCalendar fechaInicio = new GregorianCalendar();
            fechaInicio.setTime(dateInicio.getDate());
            fechaInicio.set(Calendar.HOUR_OF_DAY, (Integer) timeInicioHora.getValue());
            fechaInicio.set(Calendar.MINUTE, (Integer) timeInicioMinuto.getValue());
            fechaInicio.set(Calendar.SECOND, 0);

            GregorianCalendar fechaFin = new GregorianCalendar();
            fechaFin.setTime(dateFin.getDate());
            fechaFin.set(Calendar.HOUR_OF_DAY, (Integer) timeFinHora.getValue());
            fechaFin.set(Calendar.MINUTE, (Integer) timeFinMinuto.getValue());
            fechaFin.set(Calendar.SECOND, 0);

            // Registrar la reserva
            boolean exito = facade.registrarReserva(clienteId, agenciaId, fechaInicio, fechaFin);

            if (exito) {
                activar(false);
                limpiar();
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error al registrar la reserva: " + e.getMessage(), 
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAgencia;
    private javax.swing.JLabel lblDniCliente;
    // End of variables declaration//GEN-END:variables
    // Añadir después de las variables declaration
    private JDateChooser dateInicio;
    private JDateChooser dateFin;
    private FacadeAlquiler facade;
    private JSpinner timeInicioHora;
    private JSpinner timeInicioMinuto;
    private JSpinner timeFinHora;
    private JSpinner timeFinMinuto;
}
