/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import java.awt.Color;
import java.awt.Container;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import logica.GestorSesion;

/**
 *
 * @author ArcosArce
 */
public class panAdministradores extends javax.swing.JPanel {

    /**
     * Creates new form panAdministradores
     */
    public panAdministradores() {
        initComponents();
        JPanel panel = new panInicio();
        showPanel(panel);
    }
            
    private void showPanel(JPanel panel) {
        panContenido.removeAll();

//        panel.setSize(panContenido.getSize());
//        panel.setLocation(0, 0);
        
        panContenido.add(panel);

        panContenido.revalidate();
        panContenido.repaint();

        panel.setVisible(true);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panFondo = new javax.swing.JPanel();
        panContenido = new javax.swing.JPanel();
        btnInicio = new BotonPersonalizado("Inicio",botonMenu,presionadoMenu,encimaMenu);
        btnAgencias = new BotonPersonalizado("Inicio",botonMenu,presionadoMenu,encimaMenu);
        btnGarajes = new BotonPersonalizado("Inicio",botonMenu,presionadoMenu,encimaMenu);
        jToggleButton1 = new javax.swing.JToggleButton();
        btnClientes = new BotonPersonalizado("Inicio",botonMenu,presionadoMenu,encimaMenu);
        btnAutomoviles = new BotonPersonalizado("Inicio",botonMenu,presionadoMenu,encimaMenu);
        btnPagos = new BotonPersonalizado("Inicio",botonMenu,presionadoMenu,encimaMenu);
        btnReservas = new BotonPersonalizado("Inicio",botonMenu,presionadoMenu,encimaMenu);

        panFondo.setBackground(new java.awt.Color(8, 100, 60));

        panContenido.setBackground(new java.awt.Color(255, 255, 255));
        panContenido.setLayout(new java.awt.BorderLayout());

        btnInicio.setBackground(new java.awt.Color(30, 30, 30));
        btnInicio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Inicio");
        btnInicio.setHideActionText(true);
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnAgencias.setBackground(new java.awt.Color(30, 30, 30));
        btnAgencias.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnAgencias.setForeground(new java.awt.Color(255, 255, 255));
        btnAgencias.setText("Agencias");
        btnAgencias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAgencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgenciasActionPerformed(evt);
            }
        });

        btnGarajes.setBackground(new java.awt.Color(30, 30, 30));
        btnGarajes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnGarajes.setForeground(new java.awt.Color(255, 255, 255));
        btnGarajes.setText("Garajes");
        btnGarajes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGarajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGarajesActionPerformed(evt);
            }
        });

        jToggleButton1.setBackground(new java.awt.Color(255, 0, 51));
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("Cerrar Sesión");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        btnClientes.setBackground(new java.awt.Color(30, 30, 30));
        btnClientes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setText("Clientes");
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnAutomoviles.setBackground(new java.awt.Color(30, 30, 30));
        btnAutomoviles.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnAutomoviles.setForeground(new java.awt.Color(255, 255, 255));
        btnAutomoviles.setText("Automoviles");
        btnAutomoviles.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAutomoviles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomovilesActionPerformed(evt);
            }
        });

        btnPagos.setBackground(new java.awt.Color(30, 30, 30));
        btnPagos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnPagos.setForeground(new java.awt.Color(255, 255, 255));
        btnPagos.setText("Gestion de Pagos");
        btnPagos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosActionPerformed(evt);
            }
        });

        btnReservas.setBackground(new java.awt.Color(30, 30, 30));
        btnReservas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnReservas.setForeground(new java.awt.Color(255, 255, 255));
        btnReservas.setText("Reservas");
        btnReservas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panFondoLayout = new javax.swing.GroupLayout(panFondo);
        panFondo.setLayout(panFondoLayout);
        panFondoLayout.setHorizontalGroup(
            panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgencias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGarajes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAutomoviles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(panContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(17, 17, 17))
        );
        panFondoLayout.setVerticalGroup(
            panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFondoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jToggleButton1)
                .addGap(18, 18, 18)
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnAgencias, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGarajes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAutomoviles, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        JPanel panel = new panInicio();
        showPanel(panel);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnAgenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgenciasActionPerformed
        JPanel panel = new panAgencias();
        showPanel(panel);
    }//GEN-LAST:event_btnAgenciasActionPerformed

    private void btnGarajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGarajesActionPerformed
        JPanel panel = new panGarajes();
        showPanel(panel);
    }//GEN-LAST:event_btnGarajesActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        cerrarSesion();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        JPanel panel = new panClientes();
        showPanel(panel);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnAutomovilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomovilesActionPerformed
        JPanel panel = new panAutomoviles();
        showPanel(panel);
    }//GEN-LAST:event_btnAutomovilesActionPerformed

    private void btnPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosActionPerformed
        JPanel panel = new panPagos();
        showPanel(panel);
    }//GEN-LAST:event_btnPagosActionPerformed

    private void btnReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasActionPerformed
        JPanel panel = new panReservas();
        showPanel(panel);
    }//GEN-LAST:event_btnReservasActionPerformed
    
    /**
    * Método para cerrar la sesión actual y regresar al login
    */
   private void cerrarSesion() {
       try {
           // Confirmar acción con el usuario
           int respuesta = JOptionPane.showConfirmDialog(
               this,
               "¿Está seguro que desea cerrar la sesión?",
               "Confirmar cierre de sesión",
               JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE
           );

           if (respuesta == JOptionPane.YES_OPTION) {
               // Cerrar la sesión usando el GestorSesion
               GestorSesion.getInstance().cerrarSesion();

               // Mostrar mensaje de confirmación
               mostrarExito("Sesión cerrada correctamente");

               // Regresar al panel de login
               regresarAlLogin();
           }

       } catch (Exception e) {
           mostrarError("Error al cerrar sesión: " + e.getMessage());
           System.err.println("Error en cerrar sesión: " + e.getMessage());
       }
   }

   /**
    * Regresa al panel de login
    */
    private void regresarAlLogin() {
        try {
            java.awt.Container parent = this.getParent();
            while (parent != null && !(parent instanceof FrmPrincipal2)) {
                parent = parent.getParent();
            }

            if (parent instanceof FrmPrincipal2) {
                FrmPrincipal2 ventanaPrincipal = (FrmPrincipal2) parent;
                ventanaPrincipal.mostrarLogin(); // Usar el método centralizado
            }
        } catch (Exception e) {
            mostrarError("Error al regresar al login: " + e.getMessage());
        }
    }
   private void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    private void mostrarExito(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Información", JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
    * Método alternativo para cerrar sesión sin confirmación (para casos especiales)
    */
   private void cerrarSesionDirecto() {
       try {
           // Cerrar sesión directamente
           GestorSesion.getInstance().cerrarSesion();

           // Regresar al login
           regresarAlLogin();

       } catch (Exception e) {
           mostrarError("Error al cerrar sesión: " + e.getMessage());
       }
   }

   /**
    * Verificar si hay sesión activa antes de permitir operaciones
    */
   private boolean verificarSesionActiva() {
       if (!GestorSesion.getInstance().haySesionActiva()) {
           mostrarError("Su sesión ha expirado. Por favor, inicie sesión nuevamente.");
           regresarAlLogin();
           return false;
       }
       return true;
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgencias;
    private javax.swing.JButton btnAutomoviles;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnGarajes;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnPagos;
    private javax.swing.JButton btnReservas;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel panContenido;
    private javax.swing.JPanel panFondo;
    // End of variables declaration//GEN-END:variables
    private Color presionadoMenu = new Color(60,60,60);
    private Color encimaMenu = new Color(50,50,50);
    private Color botonMenu= new Color(30,30,30);
}
