/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import logica.GestorSesion;

/**
 *
 * @author ArcosArce
 */
public class panEmpleados extends javax.swing.JPanel {

    /**
     * Creates new form panAdministradores
     */
    public panEmpleados() {
        initComponents();
    }
            
    private void showPanel(JPanel panel) {
        panContenido.removeAll();

        panel.setSize(panContenido.getSize());
        panel.setLocation(0, 0);
        
        panContenido.add(panel);

        panContenido.revalidate();
        panContenido.repaint();

        panel.setVisible(true);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panFondo = new javax.swing.JPanel();
        panContenido = new javax.swing.JPanel();
        btnInicio = new BotonPersonalizado("Inicio",botonMenu,presionadoMenu,encimaMenu);
        btnPrestamos = new BotonPersonalizado("Inicio",botonMenu,presionadoMenu,encimaMenu);
        btnAutomovil = new BotonPersonalizado("Inicio",botonMenu,presionadoMenu,encimaMenu);
        jButton1 = new javax.swing.JButton();
        btnCliente = new BotonPersonalizado("Inicio",botonMenu,presionadoMenu,encimaMenu);

        panFondo.setBackground(new java.awt.Color(8, 100, 60));

        panContenido.setBackground(new java.awt.Color(255, 255, 255));
        panContenido.setLayout(new java.awt.BorderLayout());

        btnInicio.setBackground(new java.awt.Color(30, 30, 30));
        btnInicio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("  Inicio");
        btnInicio.setHideActionText(true);
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnPrestamos.setBackground(new java.awt.Color(30, 30, 30));
        btnPrestamos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnPrestamos.setForeground(new java.awt.Color(255, 255, 255));
        btnPrestamos.setText("  Reservas");
        btnPrestamos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamosActionPerformed(evt);
            }
        });

        btnAutomovil.setBackground(new java.awt.Color(30, 30, 30));
        btnAutomovil.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnAutomovil.setForeground(new java.awt.Color(255, 255, 255));
        btnAutomovil.setText("  Automoviles");
        btnAutomovil.setActionCommand("");
        btnAutomovil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAutomovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomovilActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cerrar sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCliente.setBackground(new java.awt.Color(30, 30, 30));
        btnCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCliente.setText("Cliente");
        btnCliente.setActionCommand("");
        btnCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panFondoLayout = new javax.swing.GroupLayout(panFondo);
        panFondo.setLayout(panFondoLayout);
        panFondoLayout.setHorizontalGroup(
            panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrestamos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addComponent(btnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addComponent(btnAutomovil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );
        panFondoLayout.setVerticalGroup(
            panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFondoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btnPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAutomovil, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        JPanel panel = new panInicio();
        showPanel(panel);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamosActionPerformed
        JPanel panel = new panReservasEmpleado();
        showPanel(panel);
    }//GEN-LAST:event_btnPrestamosActionPerformed

    private void btnAutomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomovilActionPerformed
        JPanel panel = new panAutomovilesEmpleado();
        showPanel(panel);
    }//GEN-LAST:event_btnAutomovilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cerrarSesion();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        JPanel panel = new panClientesEmpleado();
        showPanel(panel);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClienteActionPerformed
    private void cerrarSesion() {
       try {
           // Confirmar acción con el usuario
           int respuesta = JOptionPane.showConfirmDialog(
               this,
               "¿Está seguro que desea cerrar la sesión?",
               "Confirmar cierre de sesión",
               JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE
           );

           if (respuesta == JOptionPane.YES_OPTION) {
               // Cerrar la sesión usando el GestorSesion
               GestorSesion.getInstance().cerrarSesion();

               // Mostrar mensaje de confirmación
               mostrarExito("Sesión cerrada correctamente");

               // Regresar al panel de login
               regresarAlLogin();
           }

       } catch (Exception e) {
           mostrarError("Error al cerrar sesión: " + e.getMessage());
           System.err.println("Error en cerrar sesión: " + e.getMessage());
       }
   }

   /**
    * Regresa al panel de login
    */
    private void regresarAlLogin() {
        try {
            java.awt.Container parent = this.getParent();
            while (parent != null && !(parent instanceof FrmPrincipal2)) {
                parent = parent.getParent();
            }

            if (parent instanceof FrmPrincipal2) {
                FrmPrincipal2 ventanaPrincipal = (FrmPrincipal2) parent;
                ventanaPrincipal.mostrarLogin(); // Usar el método centralizado
            }
        } catch (Exception e) {
            mostrarError("Error al regresar al login: " + e.getMessage());
        }
    }
   private void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    private void mostrarExito(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Información", JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
    * Método alternativo para cerrar sesión sin confirmación (para casos especiales)
    */
   private void cerrarSesionDirecto() {
       try {
           // Cerrar sesión directamente
           GestorSesion.getInstance().cerrarSesion();

           // Regresar al login
           regresarAlLogin();

       } catch (Exception e) {
           mostrarError("Error al cerrar sesión: " + e.getMessage());
       }
   }

   /**
    * Verificar si hay sesión activa antes de permitir operaciones
    */
   private boolean verificarSesionActiva() {
       if (!GestorSesion.getInstance().haySesionActiva()) {
           mostrarError("Su sesión ha expirado. Por favor, inicie sesión nuevamente.");
           regresarAlLogin();
           return false;
       }
       return true;
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutomovil;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnPrestamos;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panContenido;
    private javax.swing.JPanel panFondo;
    // End of variables declaration//GEN-END:variables
    private Color presionadoMenu = new Color(60,60,60);
    private Color encimaMenu = new Color(50,50,50);
    private Color botonMenu= new Color(30,30,30);
}
