/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import datos.DALUsuario;
import entidades.Usuario;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import logica.GestorSesion;

/**
 *
 * @author ArcosArce
 */
public class panLogin extends javax.swing.JPanel {

    /**
     * Creates new form panLogin
     */
    public panLogin() {
        initComponents();
        configurarEnterParaLogin();
    }
    
    private void configurarEnterParaLogin() {
        // KeyListener para el campo de identificación
        txtIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    iniciarSesion();
                }
            }
        });

        // KeyListener para el campo de contraseña
        txtContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    iniciarSesion();
                }
            }
        });
    }
    private void showPanel(JPanel panel) {
        panContenido.removeAll();

        panel.setSize(panContenido.getSize());
        panel.setLocation(0, 0);
        
        panContenido.add(panel);

        panContenido.revalidate();
        panContenido.repaint();

        panel.setVisible(true);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panContenido = new javax.swing.JPanel();
        jPanel1 = new PanelPersonalizado()
        ;
        txtIdentificacion = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnIniciarSesion = new BotonPersonalizado("Inicio",botonMenu,presionadoMenu,encimaMenu);
        btnMostrarContrasena = new BotonPersonalizado("Inicio",botonMenu,presionadoMenu,encimaMenu);
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        panContenido.setBackground(new java.awt.Color(8, 100, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtIdentificacion.setBorder(null);

        txtContrasena.setBorder(null);

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Iniciar sesión en");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("AUTORENT");

        btnIniciarSesion.setBackground(new java.awt.Color(8, 100, 60));
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        btnMostrarContrasena.setBackground(new java.awt.Color(8, 100, 60));
        btnMostrarContrasena.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarContrasena.setText("Mostrar");
        btnMostrarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarContrasenaActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(btnIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(88, 88, 88)
                        .addComponent(btnMostrarContrasena))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnMostrarContrasena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panContenidoLayout = new javax.swing.GroupLayout(panContenido);
        panContenido.setLayout(panContenidoLayout);
        panContenidoLayout.setHorizontalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panContenidoLayout.createSequentialGroup()
                .addGap(575, 575, 575)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(572, Short.MAX_VALUE))
        );
        panContenidoLayout.setVerticalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panContenidoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        iniciarSesion();
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnMostrarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarContrasenaActionPerformed
        toggleMostrarContrasena();
    }//GEN-LAST:event_btnMostrarContrasenaActionPerformed
    /**
     * Método principal para iniciar sesión
     */
    private void iniciarSesion() {
        // Obtener credenciales
        String identificacion = txtIdentificacion.getText().trim();
        String contrasena = new String(txtContrasena.getPassword());
        
        // Validaciones básicas en el cliente
        if (identificacion.isEmpty()) {
            mostrarError("Por favor, ingrese su identificación");
            txtIdentificacion.requestFocus();
            return;
        }
        
        if (contrasena.isEmpty()) {
            mostrarError("Por favor, ingrese su contraseña");
            txtContrasena.requestFocus();
            return;
        }
        
        // Deshabilitar botón mientras se autentica
        btnIniciarSesion.setEnabled(false);
        btnIniciarSesion.setText("Autenticando...");
        
        try {
            // Intentar autenticación
            DALUsuario usuarioDAO = new DALUsuario();
            Usuario usuario = usuarioDAO.autenticarUsuario(identificacion, contrasena);

            if (usuario != null) {
                GestorSesion.getInstance().iniciarSesion(usuario);
                mostrarExito("Bienvenido, " + usuario.getNombre());
                abrirMenuSegunRol(usuario);
            } else {
                mostrarError("Identificación o contraseña incorrectas");
                limpiarCampos();
            }
            
        } catch (Exception e) {
            mostrarError("Error inesperado: " + e.getMessage());
            System.err.println("Error en inicio de sesión: " + e.getMessage());
        } finally {
            // Rehabilitar botón
            btnIniciarSesion.setEnabled(true);
            btnIniciarSesion.setText("Iniciar sesión");
        }
    }
    /**
     * Abre el menú correspondiente según el rol del usuario
     */
    private void abrirMenuSegunRol(Usuario usuario) {
        try {
            // Obtener la ventana principal
            java.awt.Container parent = this.getParent();
            while (parent != null && !(parent instanceof FrmPrincipal2)) {
                parent = parent.getParent();
            }

            if (parent instanceof FrmPrincipal2) {
                FrmPrincipal2 ventanaPrincipal = (FrmPrincipal2) parent;

                if (usuario.esAdministrador()) {
                    ventanaPrincipal.mostrarMenuAdministrador();
                } else if (usuario.esEmpleadoAgencia()) {
                    ventanaPrincipal.mostrarMenuEmpleado();
                }
            }
        } catch (Exception e) {
            mostrarError("Error al abrir el menú: " + e.getMessage());
        }
    }
    
    /**
     * Alterna la visibilidad de la contraseña
     */
    private void toggleMostrarContrasena() {
        if (txtContrasena.getEchoChar() == 0) {
            // Ocultar contraseña
            txtContrasena.setEchoChar('•');
            btnMostrarContrasena.setText("Mostrar");
        } else {
            // Mostrar contraseña
            txtContrasena.setEchoChar((char) 0);
            btnMostrarContrasena.setText("Ocultar");
        }
    }
    
    /**
     * Limpia los campos del formulario
     */
    private void limpiarCampos() {
        txtContrasena.setText("");
        txtIdentificacion.requestFocus();
    }
    
    /**
     * Muestra un mensaje de error
     */
    private void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    /**
     * Muestra un mensaje de éxito
     */
    private void mostrarExito(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Bienvenido", JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnMostrarContrasena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panContenido;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtIdentificacion;
    // End of variables declaration//GEN-END:variables
    private Color presionadoMenu = new Color(38,130,90);
    private Color encimaMenu = new Color(28,120,80);
    private Color botonMenu= new Color(8,100,60);

}
